INSERT INTO `sql11446779`.`car_brands` (`brand_id`, `decrp`, `brand`) VALUES ('1', 'Toyota Motor Corporation is a Japanese multinational automotive manufacturer headquartered in Toyota City, Aichi, Japan. It was founded by Kiichiro Toyoda and incorporated on August 28, 1937.', 'Toyota ');
INSERT INTO `sql11446779`.`car_brands` (`brand_id`, `decrp`, `brand`) VALUES ('2', 'Mercedes-Benz, commonly referred to as Mercedes, is a German automotive luxury brand headquartered in Stuttgart, Baden-Württemberg, Germany. Mercedes-Benz produces luxury vehicles and commercial vehicles. The first Mercedes-Benz brand name vehicles were produced in 1926.', 'Mercedes');
INSERT INTO `sql11446779`.`car_brands` (`brand_id`, `decrp`, `brand`) VALUES ('3', 'Bayerische Motoren Werke AG, commonly referred to as BMW, is a German multinational corporate manufacturer of luxury vehicles and motorcycles headquartered in Munich, Bavaria, Germany.', 'BMW');
INSERT INTO `sql11446779`.`car_brands` (`brand_id`, `decrp`, `brand`) VALUES ('4', 'Honda Motor Company, Ltd. is a Japanese public multinational conglomerate manufacturer of automobiles, motorcycles, and power equipment, headquartered in Minato, Tokyo, Japan', 'Honda ');
INSERT INTO `sql11446779`.`car_brands` (`brand_id`, `decrp`, `brand`) VALUES ('5', 'Chevrolet-branded vehicles are sold in most automotive markets worldwide. In Oceania, Chevrolet is represented by Holden Special Vehicles, having returned to the region in 2018 after a 50-year absence with the launching of the Camaro and Silverado pickup truck (HSV was partially and formerly owned by GM subsidiary Holden, which GM retired in 2021).', 'Chevrolet');
INSERT INTO `sql11446779`.`car_brands` (`brand_id`, `decrp`, `brand`) VALUES ('6', 'Ford Motor Company is an American multinational automobile manufacturer headquartered in Dearborn, Michigan, United States. It was founded by Henry Ford and incorporated on June 16, 1903. The company sells automobiles and commercial vehicles under the Ford brand, and luxury cars under its Lincoln luxury brand.', 'Ford');
INSERT INTO `sql11446779`.`car_brands` (`brand_id`, `decrp`, `brand`) VALUES ('7', "Jeeps current product range consists solely of sport utility vehicles – both crossovers and fully off-road worthy SUVs and models, including one pickup truck. Previously, Jeep\'s range included other pick-ups, as well as small vans, and a few roadsters.", 'Jeep');
INSERT INTO `sql11446779`.`car_brands` (`brand_id`, `decrp`, `brand`) VALUES ('8', 'Dr.-Ing. h.c. F. Porsche AG, usually shortened to Porsche, is a German automobile manufacturer specializing in high-performance sports cars, SUVs and sedans, headquartered in Stuttgart, Baden-Württemberg, Germany.', 'Porsche');
INSERT INTO `sql11446779`.`car_brands` (`brand_id`, `decrp`, `brand`) VALUES ('9', 'Nissan Motor Co., Ltd. is a Japanese multinational automobile manufacturer headquartered in Nishi-ku, Yokohama, Japan. The company sells its vehicles under the Nissan, Infiniti, and Datsun brands. The company traces its name to the Nissan zaibatsu, now called Nissan Group.', 'Nissan');
INSERT INTO `sql11446779`.`car_brands` (`brand_id`, `decrp`, `brand`) VALUES ('10', 'Lexus is the luxury vehicle division of the Japanese automaker Toyota. The Lexus brand is marketed in more than 70 countries and territories worldwide and is Japans largest-selling make of premium cars. It has ranked among the 10 largest Japanese global brands in market value. Lexus is headquartered in Nagoya, Japan.', 'Lexus');
INSERT INTO `sql11446779`.`car_brands` (`brand_id`, `decrp`, `brand`) VALUES ('11', 'Audi AG is a German automotive manufacturer of luxury vehicles headquartered in Ingolstadt, Bavaria, Germany. As a subsidiary of its parent company, the Volkswagen Group, Audi produces vehicles in nine production facilities worldwide.', 'Audi');
INSERT INTO `sql11446779`.`car_brands` (`brand_id`, `decrp`, `brand`) VALUES ('12', 'Hyundai Motor Company is a South Korean multinational automotive manufacturer headquartered in Seoul, South Korea. Hyundai Motor Company was founded in 1967', 'Hyundai ');
INSERT INTO `sql11446779`.`car_brands` (`brand_id`, `decrp`, `brand`) VALUES ('13', 'Mazda Motor Corporation is a Japanese multinational automaker based in Fuchū, Hiroshima, Japan. In 2015, Mazda produced 1.5 million vehicles for global sales, the majority of which were produced in the companys Japanese plants, with the remainder coming from a variety of other plants worldwide', 'Mazda ');
INSERT INTO `sql11446779`.`car_brands` (`brand_id`, `decrp`, `brand`) VALUES ('14', 'Tesla, Inc. is an American electric vehicle and clean energy company based in Palo Alto, California, United States. Tesla designs and manufactures electric cars, battery energy storage from home to grid-scale, solar panels and solar roof tiles, and related products and services', 'Tesal');
INSERT INTO `sql11446779`.`car_brands` (`brand_id`, `decrp`, `brand`) VALUES ('15', 'Kia Corporation is a South Korean multinational automobile manufacturer headquartered in Seoul, South Korea. It is South Koreas second largest automobile manufacturer after parent company Hyundai Motor Company, with sales of over 2.8 million vehicles in 2019', 'Kia');
INSERT INTO `sql11446779`.`car_brands` (`brand_id`, `decrp`, `brand`) VALUES ('16', 'Infinity is that which is boundless or endless, or something that is larger than any real or natural number. It is often denoted by the infinity symbol. Since the time of the ancient Greeks, the philosophical nature of infinity was the subject of many discussions among philosopher', 'Infinity');
INSERT INTO `sql11446779`.`car_brands` (`brand_id`, `decrp`, `brand`) VALUES ('17', 'Mitsubishi Motors Corporation is a Japanese multinational automotive manufacturer headquartered in Minato, Tokyo, Japan. In 2011, Mitsubishi Motors was the sixth-largest Japanese automaker and the 19th-largest worldwide by production. ', 'Mitsubishi ');
INSERT INTO `sql11446779`.`car_brands` (`brand_id`, `decrp`, `brand`) VALUES ('18', 'Suzuki Motor Corporation is a Japanese multinational corporation headquartered in Minami-ku, Hamamatsu, Japan. Suzuki manufactures automobiles, four-wheel drive vehicles, motorcycles, all-terrain vehicles, outboard marine engines, wheelchairs and a variety of other small internal combustion engines.', 'Suzuki');
INSERT INTO `sql11446779`.`car_brands` (`brand_id`, `decrp`, `brand`) VALUES ('19', 'Peugeot is a French brand of automobiles owned by Stellantis. The family business that preceded the current Peugeot companies was founded in 1810, with a steel foundry that soon started making hand tools and kitchen equipment, and then bicycles. On 20 November 1858, Émile Peugeot applied for the lion trademark.', 'Peugeot');
INSERT INTO `sql11446779`.`car_brands` (`brand_id`, `decrp`, `brand`) VALUES ('20', 'Ferrari S.p.A. is an Italian luxury sports car manufacturer based in Maranello, Italy. Founded by Enzo Ferrari in 1939 out of the Alfa Romeo race division as Auto Avio Costruzioni, the company built its first car in 1940, and produced its first Ferrari-badged car in 1947', 'Ferrari ');



INSERT INTO `sql11446779`.`car_types` (`typeCar_id`, `type_desc`, `car_type`) VALUES ('1', "A sedan has four doors and a traditional trunk. Like vehicles in many categories, they're available in a range of sizes from small (subcompact vehicles like Nissan Versa and Kia Rio) to compacts (Honda Civic, Toyota Corolla) to mid-size (Honda Accord, Nissan Altima), and full-size (Toyota Avalon, Dodge Charger). Luxury brands like Mercedes-Benz and Lexus have sedans in similar sizes as well.", 'SEDAN');
INSERT INTO `sql11446779`.`car_types` (`typeCar_id`, `type_desc`, `car_type`) VALUES ('2',"A coupe has historically been considered a two-door car with a trunk and a solid roof. This would include cars like a Ford Mustang or Audi A5—or even two-seat sports cars like the Chevrolet Corvette and Porsche Boxster. Recently, however, car companies have started to apply the word 'coupe' to four-door cars or crossovers with low, sleek rooflines that they deem 'coupe-like.' This includes vehicles as disparate as a Mercedes-Benz CLS sedan and BMW X6 SUV. At Car and Driver, we still consider a coupe to be a two-door car.", 'COUPE');
INSERT INTO `sql11446779`.`car_types` (`typeCar_id`, `type_desc`, `car_type`) VALUES ('3', "These are the sportiest, hottest, coolest-looking coupes and convertibles—low to the ground, sleek, and often expensive. They generally are two-seaters, but sometimes have small rear seats as well. Cars like the Porsche 911 and Mazda Miata are typical sports cars, but you can stretch the definition to include muscle cars like the Ford Mustang and Dodge Challenger. Then there are the high-end exotic dream cars with sky-high price tags for the one percent, cars like the Ferrari 488 GTB and Aston Martin Vantage, which stop traffic with their spaceship looks.", 'SPORTS CAR');
INSERT INTO `sql11446779`.`car_types` (`typeCar_id`, `type_desc`, `car_type`) VALUES ('4', "Wagons are similar to sedans but have an extended roofline and a hatch door at the rear instead of a trunk. Some, like the Subaru Outback or Audi A4 Allroad, have elevated ground clearance and some rugged body cladding to make them more like a sport-utility vehicle (SUV), but they are nonetheless closely related to sedans. Wagons have fallen from favor during the past few decades and there are relatively few available for sale in the United States.", 'STATION WAGON');
INSERT INTO `sql11446779`.`car_types` (`typeCar_id`, `type_desc`, `car_type`) VALUES ('5', "Traditionally, the term 'hatchback' has meant a compact or subcompact sedan with a squared-off roof and a rear flip-up hatch door that provides access to the vehicle's cargo area instead of a conventional trunk. The Volkswagen Golf and Kia Rio are two typical hatchbacks. More recently, rear hatches have found their way on to some larger cars, like the Audi A7 and Kia Stinger. They look like sedans, but they actually have a steeply raked hatchback that affords easier accessibility to the cargo area and greater carrying capacity than a traditional trunk would.", 'HATCHBACK');
INSERT INTO `sql11446779`.`car_types` (`typeCar_id`, `type_desc`, `car_type`) VALUES ('6', "Does the roof retract into the body leaving the passenger cabin open to the elements? If so, it's a convertible. Most convertibles have a fully powered fabric roof that folds down, but a few have to be lowered by hand. There are also a number of models with a retractable hardtop, as well as several unusual quasi-convertibles (called 'targa tops') like the Mazda MX-5 Miata RF, Porsche 911 Targa and Corvette; only the forward section of their roofs retracts or can be removed by hand.", 'CONVERTIBLE');
INSERT INTO `sql11446779`.`car_types` (`typeCar_id`, `type_desc`, `car_type`) VALUES ('7', "SUVs—often also referred to as crossovers—tend to be taller and boxier than sedans, offer an elevated seating position, and have more ground clearance than a car. They include a station wagon-like cargo area that is accessed through a flip-up rear hatch door, and many offer all-wheel drive. The larger ones have three rows of seats. Sizes start at subcompact (Hyundai Kona, Nissan Kicks), mid-size, and go all the way to full-size (Ford Expedition, Chevrolet Tahoe). Luxury brands offer many SUV models in most of the same size categories.", 'SPORT-UTILITY VEHICLE (SUV)');
INSERT INTO `sql11446779`.`car_types` (`typeCar_id`, `type_desc`, `car_type`) VALUES ('8', "Minivans are the workhorses of the family-car world, the best at carrying people and cargo in an efficient package. They're called minivans but they are far from 'mini.' That's because they are tall boxes-on-wheels with sliding side doors for easy access and a rear hatch that opens to a large cargo area. Most minivans have adjustable seats in their second and third rows that often can be removed or even folded into the floor to create a huge open cargo bay. The Honda Odyssey and Chrysler Pacifica are great examples of the breed.", 'MINIVAN');